name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the app
        run: yarn build

      - name: Setup SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy
        run: |
          rsync -avz --delete \
            --exclude='/node_modules' \
            --exclude='/src' \
            --exclude='/.git' \
            --exclude='/.github' \
            $GITHUB_WORKSPACE/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/${{ secrets.SSH_HOST }}
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd /home/${{ secrets.SSH_USER }}/${{ secrets.SSH_HOST }} && yarn install --production && pm2 restart \"yarn start\""
